### ISSUE TITLE
Implement SessionlessTokenInterface in HashToken

### ISSUE THREAD

**Issue by sebastiansommer** [flownative/flow-token-auth#4]
I noticed that the [HashToken](https://github.com/flownative/flow-token-auth/blob/master/Classes/Security/HashToken.php) does not implement the [SessionlessTokenInterface](https://github.com/neos/flow/blob/master/Classes/Security/Authentication/Token/SessionlessTokenInterface.php). Is there any reason for it? 

Im mostly using this package for simple server to server requests. For that, it wouldn't be necessary to start a new session for each request.

**Comment by kdambekalns** [comment]
Hm… the PR for this looked so innocent, but now I saw https://github.com/flownative/flow-token-auth/pull/1/commits/aabfa4d773cc1fe708c04e4df78f3e5d27a69444

@kitsunet Do you recall the reasons for that?

**Comment by kdambekalns** [comment]
By now we found out the reasons (it was supposed to start a session, so that further requests "just work"). But it's solved by now, the latest release supports both, session-based and sessionless use.
